apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-register-database
  labels:
    app.kubernetes.io/name: gym-register-database
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gym-register-database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gym-register-database
    spec:
      serviceAccountName: gym-register-database
      containers:
        - name: main
          image: {{ include "gymregister.image.name" (dict "name" "gym-register-database") }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy | default "IfNotPresent" }}
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gym-register-database-superuser-credentials
                key: password
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
