apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-register-database
  labels:
    app.kubernetes.io/name: gym-register-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gym-register-database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gym-register-database
      annotations:
        checksum/gym-register-database-superuser-credentials: {{ include (print $.Template.BasePath "/database/superuser-credentials.yaml") . | sha256sum }}
    spec:
      serviceAccountName: gym-register-database
      containers:
        - name: main
          image: {{ include "gymregister.image.name" (dict "name" "gym-register-database" "Chart" .Chart) }}
          imagePullPolicy: {{ (.Values.image).imagePullPolicy | default "IfNotPresent" }}
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gym-register-database-superuser-credentials
                key: password
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
