apiVersion: v1
kind: Service
metadata:
  name: gym-register-database
spec:
  selector:
    app.kubernetes.io/name: gym-register-database
  ports:
    - port: 5432
      targetPort: http
      protocol: TCP
      name: http
