apiVersion: v1
kind: Secret
metadata:
  name: gym-register-database-superuser-credentials
data:
  password: {{ (((.Values.database).credentials).superuser).password | default (randAlphaNum 16) | b64enc }}
