apiVersion: v1
kind: Service
metadata:
  name: gym-register-app
spec:
  selector:
    app.kubernetes.io/name: gym-register-app
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
